version: '2.2'

#networks:
#  proxy:
#    external:
#      name: proxy_network

services:
  nginx:
    container_name: proxy_nginx
    image: nginx:stable-alpine
    restart: always
#    networks:
#      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../volumes/conf.d:/etc/nginx/conf.d:rw
      - ../volumes/vhost.d:/etc/nginx/vhost.d:rw
      - ../volumes/html:/usr/share/nginx/html:rw
      - ../volumes/certs:/etc/nginx/certs:ro
    network_mode: bridge
    logging:
      driver: "json-file"
      options: { max-size: "50k", max-file: "3" }

  generator:
    container_name: proxy_generator
    image: nginxproxy/docker-gen
    command: -notify-sighup proxy_nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: always
#    networks:
#      - proxy
    volumes_from:
      - nginx
    volumes:
      - ../etc/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge
    logging:
      driver: "json-file"
      options: { max-size: "50k", max-file: "3" }

  letsencrypt:
    container_name: proxy_letsencrypt
    image: nginxproxy/acme-companion
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: proxy_nginx
      NGINX_DOCKER_GEN_CONTAINER: proxy_generator
      REUSE_ACCOUNT_KEYS: 1
      REUSE_PRIVATE_KEYS: 1
#    networks:
#      - proxy
    volumes_from:
      - nginx
    volumes:
      - ../volumes/certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
    logging:
      driver: "json-file"
      options: { max-size: "50k", max-file: "3" }

volumes:
  acme:
