version: '2.2'

networks:
  registry:
    external:
      name: registry_network

services:
  web:
    container_name: registry_web
    image: nginx
    restart: always
    depends_on:
      - registry
    networks:
      - registry
    volumes:
      - ../web/registry:/usr/share/nginx/html:ro
    environment:
      VIRTUAL_HOST: ${REGISTRY_HOST}
      LETSENCRYPT_HOST: ${REGISTRY_HOST}
      LETSENCRYPT_EMAIL: ${REGISTRY_EMAIL}
    logging:
      driver: "json-file"
      options: { max-size: "1m", max-file: "3" }

  registry:
    container_name: registry_registry
    image: registry:${REGISTRY_VERSION}
    restart: always
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_HTTP_SECRET: ${REGISTRY_SECRET}
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/${REGISTRY_HOST}/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /certs/${REGISTRY_HOST}/key.pem
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    networks:
      - registry
    ports:
      - "${REGISTRY_PORT}:5000"
    volumes:
      - ../volumes/registry:/var/lib/registry:rw
      - ../volumes/certs:/certs:ro
      - ../volumes/auth:/auth:ro
    logging:
      driver: "json-file"
      options: { max-size: "1m", max-file: "3" }
